"use client";
import Link from "next/link";
import FeedbackForm from "@/components/FeedbackForm";
import LocaleOnly from "@/components/LocaleOnly";
const card = "rounded-[24px] border border-[var(--pal-border)] bg-white p-5 shadow-[0_5px_20px_rgba(15,23,42,0.035)] sm:p-7";
const title = "mb-4 text-xl font-extrabold text-[var(--pal-text)] sm:text-2xl";
type Section = { title: string; paragraphs: string[]; bullets?: string[] };
const privacy: Section[] = [
{title:"1. Introduction",paragraphs:["PALJALE respects user privacy and aims to minimize the information collected to provide its digital tools.","This Privacy Policy explains what information may be processed when you use PALJALE, how its tools operate and which external services we use."]},
{title:"2. File processing",paragraphs:["PALJALE's PDF, image, multimedia conversion and QR code tools are designed to process files directly in your browser.","Files selected for these tools generally do not need to be sent to a PALJALE-owned server for processing.","PALJALE does not intentionally store documents, images, audio or video processed through these browser-based tools.","However, before processing highly sensitive or legally protected information using any online service, assess the applicable security and legal requirements."]},
{title:"3. Usage information and analytics",paragraphs:["PALJALE uses Google Analytics 4, when authorized by the user, to understand general website usage and improve available tools.","We may record general events such as opening a tool, uploading a file, completing a process, encountering an error or downloading a result. These events are not intentionally designed to include file contents or filenames."],bullets:["Visited pages and browsing sessions","General interaction events","Browser, device and operating system","Approximate geographic location"]},
{title:"4. Cookies and similar technologies",paragraphs:["Analytics services may use cookies or identifiers to distinguish visits and produce usage statistics.","Their use depends on your browser configuration and your consent preferences, which you can change using the cookie preferences link."]},
{title:"5. IP addresses",paragraphs:["Google Analytics 4 may temporarily use IP addresses for technical processing and approximate geolocation. According to Google's documentation, IP addresses are not logged or stored by Google Analytics as part of its standard operation."]},
{title:"6. Information we do not request",paragraphs:["PALJALE currently does not require an account to use public tools. We do not generally ask for passwords, banking information, identification documents or sensitive personal data to use those tools."]},
{title:"7. Third-party services",paragraphs:["PALJALE uses Google Analytics for analytics, Vercel for hosting and delivery, and Formspree to receive messages submitted through the contact form.","These providers may process technical information or form contents under their own terms and privacy policies. If you submit contact details, they may be used to reply to your inquiry."]},
{title:"8. Data retention",paragraphs:["PALJALE does not intentionally retain files processed locally in the browser.","Analytics statistics and messages submitted through Formspree may be retained according to the relevant service settings and policies."]},
{title:"9. Security",paragraphs:["We take reasonable measures to reduce technical risks and maintain dependencies and tools. No Internet-connected system can guarantee absolute security."]},
{title:"10. Children's privacy",paragraphs:["PALJALE is not specifically intended to collect personal data from minors. If inappropriate disclosure is identified, we will seek to take reasonable measures."]},
{title:"11. Your rights and choices",paragraphs:["Depending on applicable laws, you may have rights of access, rectification, erasure, objection or restriction regarding personal data.","You can also manage browser cookies and local data using your browser's settings."]},
{title:"12. Changes to this policy",paragraphs:["We may revise this policy when PALJALE introduces new tools, providers, monetization or other technical and legal changes. The updated date identifies the current published version."]},
{title:"13. Controller and contact",paragraphs:["PALJALE is responsible for this notice regarding functions it operates directly. Use the contact page for privacy requests or inquiries about the service."]}
];
const terms: Section[] = [
{title:"1. Acceptance",paragraphs:["By accessing or using PALJALE, you agree to these Terms of Use. If you disagree, please do not use the available tools or services."]},
{title:"2. Service description",paragraphs:["PALJALE offers browser-based digital tools for tasks including PDF documents, images, multimedia and QR codes. Tools may be modified, expanded, replaced or withdrawn as the platform evolves."]},
{title:"3. Permitted use",paragraphs:["You may use PALJALE for lawful personal or professional purposes, provided that doing so does not infringe third-party rights.","You are responsible for ensuring you have the necessary rights to process any documents, images, audio, videos, text or other content."]},
{title:"4. Prohibited use",paragraphs:["PALJALE may not be used for illegal or fraudulent activities, or to harm the platform or others."],bullets:["Copyright infringement or other intellectual property violations","Fraud, impersonation or deception","Disruption of platform security, stability or availability","Abusive automated requests or excessive load","Introducing or distributing malware","Unauthorized access to related systems, data or infrastructure"]},
{title:"5. Responsibility for files",paragraphs:["You are responsible for files you select, process, transform, download or share using PALJALE.","PALJALE does not systematically inspect content processed locally in the browser, nor guarantee suitability for any specific purpose."]},
{title:"6. Local processing",paragraphs:["Current tools are designed to process files in the user's browser whenever technically feasible. Hosting, measurement, distribution or future functions may rely on third-party services."]},
{title:"7. Service availability",paragraphs:["We aim to keep PALJALE available, but cannot guarantee uninterrupted service or error-free operation. Maintenance, updates and external problems may cause interruptions."]},
{title:"8. Tool results",paragraphs:["We aim for accurate results, but cannot guarantee that all files will be processed or that output will match specialized software.","Check generated files before deleting originals or using results for critical purposes."]},
{title:"9. Backups",paragraphs:["Keep backup copies of important files before processing them. PALJALE is not a storage or backup service."]},
{title:"10. PALJALE intellectual property",paragraphs:["PALJALE's original visual identity, design, structure, text and brand are subject to applicable intellectual property laws. Using the site does not grant ownership rights over these elements."]},
{title:"11. Third-party software and components",paragraphs:["PALJALE may use third-party libraries and technologies subject to their respective licenses. Ownership remains with their respective rights holders."]},
{title:"12. Third-party services",paragraphs:["We may rely on external hosting, analytics, delivery and other technical providers. Their services and policies are not fully under our control."]},
{title:"13. Advertising and monetization",paragraphs:["PALJALE may introduce advertisements, affiliate links, premium features, APIs or other monetization in the future. Terms and policies may be revised accordingly."]},
{title:"14. Limitation of liability",paragraphs:["To the extent allowed by applicable law, PALJALE is not liable for losses resulting from misuse, lost original files, interruptions, incompatibilities, conversion errors or decisions based solely on generated results.","Nothing here limits liabilities that cannot legally be excluded."]},
{title:"15. Service changes",paragraphs:["PALJALE may change its tools, file limits, formats and capabilities to maintain, improve or develop the service."]},
{title:"16. Changes to these terms",paragraphs:["These Terms may be updated to reflect technical, commercial, functional or legal changes. The latest published version is identified by its date."]},
{title:"17. Privacy",paragraphs:["For details about information processing, please read our Privacy Policy."]},
{title:"18. Contact",paragraphs:["For questions about functionality, privacy, intellectual property or the service, please use our contact form."]}
];
function Sections({ data }: { data: Section[] }) { return <>{data.map(section => <section key={section.title} className={card}><h2 className={title}>{section.title}</h2>{section.paragraphs.map((p,i) => <p key={i} className={i ? "mt-4" : undefined}>{p}</p>)}{section.bullets && <ul className="mt-4 list-disc space-y-2 pl-6">{section.bullets.map(b => <li key={b}>{b}</li>)}</ul>}{section.title === "17. Privacy" && <Link href="/privacidad" className="mt-4 inline-flex font-bold text-[var(--pal-accent)]">Read Privacy Policy →</Link>}{section.title === "18. Contact" && <Link href="/contacto" className="mt-4 inline-flex font-bold text-[var(--pal-accent)]">Contact us →</Link>}</section>)}</>; }
export default function EnglishInstitutionalPage({ kind }: { kind: "privacy" | "terms" | "contact" | "about" }) {
  return <LocaleOnly language="en">{kind === "privacy" ? <Sections data={privacy}/> : kind === "terms" ? <Sections data={terms}/> : kind === "contact" ? <><FeedbackForm/><section className={card}><h2 className={title}>How can we help?</h2><p>Use the form to share your feedback, suggest new tools, report a bug or ask us a question.</p><p className="mt-3">If reporting a problem, describe what happened and which tool you used. Do not submit passwords, banking details or confidential documents.</p><p className="mt-3">Messages are processed by our form provider. Please read our <Link href="/privacidad" className="font-bold text-[var(--pal-accent)]">Privacy Policy</Link>.</p></section></> : <><section className={card}><h2 className={title}>What is PALJALE?</h2><p>PALJALE is an online digital tools project built to make everyday tasks easier, without unnecessary installations or complexity. Its categorized library helps you find useful tools in one place.</p><p className="mt-4">The platform is being developed in stages, adding solutions for documents, images, audio and more. Some categories are still under development.</p></section><section className={card}><h2 className={title}>Our purpose</h2><p>To create practical, accessible browser-based tools that eliminate unnecessary steps and improve through community feedback.</p><p className="mt-4">Whenever possible, we prioritize processing files locally in your browser to reduce external transfers.</p></section><section className="rounded-[24px] border border-[var(--pal-border)] bg-gradient-to-br from-[var(--pal-tint)] via-white to-white px-6 py-9 text-center"><p className="text-sm font-extrabold uppercase tracking-widest text-[var(--pal-accent)]">Our inspiration</p><blockquote className="mx-auto mt-5 max-w-2xl text-2xl font-extrabold leading-snug text-[var(--pal-text)]">“Technology is most valuable when it makes people&apos;s lives simpler.”</blockquote></section><section className={card}><h2 className={title}>PALJALE&apos;s creator</h2><h3 className="text-xl font-extrabold text-[var(--pal-text)]">Eduardo Muñoz Hernández</h3><p className="mt-1 font-semibold text-[var(--pal-accent)]">Industrial Engineer</p><p className="mt-5">Passionate about technology, innovation and continuous improvement, Eduardo seeks to turn ideas into practical, accessible digital tools that simplify everyday tasks.</p><p className="mt-4">PALJALE grew from a desire to learn, create and show that technology can be within everyone&apos;s reach.</p></section><section className={card}><h2 className={title}>Your feedback matters</h2><p>Your opinions help determine what to improve and which tools to develop next.</p><Link href="/contacto#opiniones" className="mt-5 inline-flex rounded-xl bg-[var(--pal-accent)] px-5 py-3 text-sm font-bold text-white">Send feedback →</Link></section></>}</LocaleOnly>;
}
